# Generated by Django 3.1.7 on 2021-10-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HOME_PAGE_ARTICALSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=250)),
                ('image', models.ImageField(upload_to='home_articals_img/')),
                ('decs', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='HOME_PAGE_IMAGE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home_img/')),
            ],
        ),
    ]
